/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.sf.RegForm;

/** 
 * MyEclipse Struts
 * Creation date: 05-24-2018
 * 
 * XDoclet definition:
 * @struts.action path="/reg" name="regForm" input="/form/reg.jsp" scope="request" validate="true"
 */
public class RegAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegForm regForm = (RegForm) form;// TODO Auto-generated method stub
		String account = regForm.getAccount();
		String password = regForm.getPassword();
		System.out.println("account:"+account+"password:"+password);
		
		System.out.println("this is struts1");
		return null;
	}
}