/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-05-29 11:56:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/java文件/tomcat/tomcat8/apache-tomcat-8.0.52/webapps/WebChat-master/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1526397396813L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>WebChat | 聊天</title>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/commonfile.jsp", out, false);
      out.write("\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/plugins/sockjs/sockjs.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"am-cf admin-main\">\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <!-- content start -->\n");
      out.write("    <div class=\"admin-content\">\n");
      out.write("        <div class=\"\" style=\"width: 80%;float:left;\">\n");
      out.write("            <!-- 聊天区 -->\n");
      out.write("            <div class=\"am-scrollable-vertical\" id=\"chat-view\" style=\"height: 510px;\">\n");
      out.write("                <ul class=\"am-comments-list am-comments-list-flip\" id=\"chat\">\n");
      out.write("                </ul>\n");
      out.write("            </div>\n");
      out.write("            <!-- 输入区 -->\n");
      out.write("            <div class=\"am-form-group am-form\">\n");
      out.write("                <textarea class=\"\" id=\"message\" name=\"message\" rows=\"5\"  placeholder=\"这里输入你想发送的信息...\"></textarea>\n");
      out.write("            </div>\n");
      out.write("            <!-- 接收者 -->\n");
      out.write("            <div class=\"\" style=\"float: left\">\n");
      out.write("                <p class=\"am-kai\">发送给 : <span id=\"sendto\">全体成员</span><button class=\"am-btn am-btn-xs am-btn-danger\" onclick=\"$('#sendto').text('全体成员')\">复位</button></p>\n");
      out.write("            </div>\n");
      out.write("            <!-- 按钮区 -->\n");
      out.write("            <div class=\"am-btn-group am-btn-group-xs\" style=\"float:right;\">\n");
      out.write("                <button class=\"am-btn am-btn-default\" type=\"button\" onclick=\"getConnection()\"><span class=\"am-icon-plug\"></span> 连接</button>\n");
      out.write("                <button class=\"am-btn am-btn-default\" type=\"button\" onclick=\"closeConnection()\"><span class=\"am-icon-remove\"></span> 断开</button>\n");
      out.write("                <button class=\"am-btn am-btn-default\" type=\"button\" onclick=\"checkConnection()\"><span class=\"am-icon-bug\"></span> 检查</button>\n");
      out.write("                <button class=\"am-btn am-btn-default\" type=\"button\" onclick=\"clearConsole()\"><span class=\"am-icon-trash-o\"></span> 清屏</button>\n");
      out.write("                <button class=\"am-btn am-btn-default\" type=\"button\" onclick=\"sendMessage()\"><span class=\"am-icon-commenting\"></span> 发送</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- 列表区 -->\n");
      out.write("        <div class=\"am-panel am-panel-default\" style=\"float:right;width: 20%;\">\n");
      out.write("            <div class=\"am-panel-hd\">\n");
      out.write("                <h3 class=\"am-panel-title\">在线列表 [<span id=\"onlinenum\"></span>]</h3>\n");
      out.write("            </div>\n");
      out.write("            <ul class=\"am-list am-list-static am-list-striped\" >\n");
      out.write("                <li>图灵机器人 <button class=\"am-btn am-btn-xs am-btn-danger\" id=\"tuling\" data-am-button>未上线</button></li>\n");
      out.write("            </ul>\n");
      out.write("            <ul class=\"am-list am-list-static am-list-striped\" id=\"list\">\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- content end -->\n");
      out.write("</div>\n");
      out.write("<a href=\"#\" class=\"am-show-sm-only admin-menu\" data-am-offcanvas=\"{target: '#admin-offcanvas'}\">\n");
      out.write("    <span class=\"am-icon-btn am-icon-th-list\"></span>\n");
      out.write("</a>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/footer.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    $(function () {\n");
      out.write("        context.init({preventDoubleContext: false});\n");
      out.write("        context.settings({compress: true});\n");
      out.write("        context.attach('#chat-view', [\n");
      out.write("            {header: '操作菜单',},\n");
      out.write("            {text: '清理', action: clearConsole},\n");
      out.write("            {divider: true},\n");
      out.write("            {\n");
      out.write("                text: '选项', subMenu: [\n");
      out.write("                {header: '连接选项'},\n");
      out.write("                {text: '检查', action: checkConnection},\n");
      out.write("                {text: '连接', action: getConnection},\n");
      out.write("                {text: '断开', action: closeConnection}\n");
      out.write("            ]\n");
      out.write("            },\n");
      out.write("            {\n");
      out.write("                text: '销毁菜单', action: function (e) {\n");
      out.write("                e.preventDefault();\n");
      out.write("                context.destroy('#chat-view');\n");
      out.write("            }\n");
      out.write("            }\n");
      out.write("        ]);\n");
      out.write("    });\n");
      out.write("    if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"){\n");
      out.write("        layer.msg('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', {\n");
      out.write("            offset: 0\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"){\n");
      out.write("        layer.msg('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', {\n");
      out.write("            offset: 0,\n");
      out.write("            shift: 6\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    $(\"#tuling\").click(function(){\n");
      out.write("        var onlinenum = $(\"#onlinenum\").text();\n");
      out.write("        if($(this).text() == \"未上线\"){\n");
      out.write("            $(this).text(\"已上线\").removeClass(\"am-btn-danger\").addClass(\"am-btn-success\");\n");
      out.write("            showNotice(\"图灵机器人加入聊天室\");\n");
      out.write("            $(\"#onlinenum\").text(parseInt(onlinenum) + 1);\n");
      out.write("        }\n");
      out.write("        else{\n");
      out.write("            $(this).text(\"未上线\").removeClass(\"am-btn-success\").addClass(\"am-btn-danger\");\n");
      out.write("            showNotice(\"图灵机器人离开聊天室\");\n");
      out.write("            $(\"#onlinenum\").text(parseInt(onlinenum) - 1)\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("    var wsServer = null;\n");
      out.write("    var ws = null;\n");
      out.write("    wsServer = \"ws://\" + location.host+\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" + \"/chatServer\";\n");
      out.write("    ws = new WebSocket(wsServer); //创建WebSocket对象\n");
      out.write("    ws.onopen = function (evt) {\n");
      out.write("        layer.msg(\"已经建立连接\", { offset: 0});\n");
      out.write("    };\n");
      out.write("    ws.onmessage = function (evt) {\n");
      out.write("        analysisMessage(evt.data);  //解析后台传回的消息,并予以展示\n");
      out.write("    };\n");
      out.write("    ws.onerror = function (evt) {\n");
      out.write("        layer.msg(\"产生异常\", { offset: 0});\n");
      out.write("    };\n");
      out.write("    ws.onclose = function (evt) {\n");
      out.write("        layer.msg(\"已经关闭连接\", { offset: 0});\n");
      out.write("    };\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 连接\n");
      out.write("     */\n");
      out.write("    function getConnection(){\n");
      out.write("        if(ws == null){\n");
      out.write("            ws = new WebSocket(wsServer); //创建WebSocket对象\n");
      out.write("            ws.onopen = function (evt) {\n");
      out.write("                layer.msg(\"成功建立连接!\", { offset: 0});\n");
      out.write("            };\n");
      out.write("            ws.onmessage = function (evt) {\n");
      out.write("                analysisMessage(evt.data);  //解析后台传回的消息,并予以展示\n");
      out.write("            };\n");
      out.write("            ws.onerror = function (evt) {\n");
      out.write("                layer.msg(\"产生异常\", { offset: 0});\n");
      out.write("            };\n");
      out.write("            ws.onclose = function (evt) {\n");
      out.write("                layer.msg(\"已经关闭连接\", { offset: 0});\n");
      out.write("            };\n");
      out.write("        }else{\n");
      out.write("            layer.msg(\"连接已存在!\", { offset: 0, shift: 6 });\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 关闭连接\n");
      out.write("     */\n");
      out.write("    function closeConnection(){\n");
      out.write("        if(ws != null){\n");
      out.write("            ws.close();\n");
      out.write("            ws = null;\n");
      out.write("            $(\"#list\").html(\"\");    //清空在线列表\n");
      out.write("            layer.msg(\"已经关闭连接\", { offset: 0});\n");
      out.write("        }else{\n");
      out.write("            layer.msg(\"未开启连接\", { offset: 0, shift: 6 });\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 检查连接\n");
      out.write("     */\n");
      out.write("    function checkConnection(){\n");
      out.write("        if(ws != null){\n");
      out.write("            layer.msg(ws.readyState == 0? \"连接异常\":\"连接正常\", { offset: 0});\n");
      out.write("        }else{\n");
      out.write("            layer.msg(\"连接未开启!\", { offset: 0, shift: 6 });\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 发送信息给后台\n");
      out.write("     */\n");
      out.write("    function sendMessage(){\n");
      out.write("        if(ws == null){\n");
      out.write("            layer.msg(\"连接未开启!\", { offset: 0, shift: 6 });\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("        var message = $(\"#message\").val();\n");
      out.write("        var to = $(\"#sendto\").text() == \"全体成员\"? \"\": $(\"#sendto\").text();\n");
      out.write("        if(message == null || message == \"\"){\n");
      out.write("            layer.msg(\"请不要惜字如金!\", { offset: 0, shift: 6 });\n");
      out.write("            return;\n");
      out.write("        }\n");
      out.write("        $(\"#tuling\").text() == \"已上线\"? tuling(message):console.log(\"图灵机器人未开启\");  //检测是否加入图灵机器人\n");
      out.write("        ws.send(JSON.stringify({\n");
      out.write("            message : {\n");
      out.write("                content : message,\n");
      out.write("                from : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\n");
      out.write("                to : to,      //接收人,如果没有则置空,如果有多个接收人则用,分隔\n");
      out.write("                time : getDateFull()\n");
      out.write("            },\n");
      out.write("            type : \"message\"\n");
      out.write("        }));\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 解析后台传来的消息\n");
      out.write("     * \"massage\" : {\n");
      out.write("     *              \"from\" : \"xxx\",\n");
      out.write("     *              \"to\" : \"xxx\",\n");
      out.write("     *              \"content\" : \"xxx\",\n");
      out.write("     *              \"time\" : \"xxxx.xx.xx\"\n");
      out.write("     *          },\n");
      out.write("     * \"type\" : {notice|message},\n");
      out.write("     * \"list\" : {[xx],[xx],[xx]}\n");
      out.write("     */\n");
      out.write("    function analysisMessage(message){\n");
      out.write("        message = JSON.parse(message);\n");
      out.write("        if(message.type == \"message\"){      //会话消息\n");
      out.write("            showChat(message.message);\n");
      out.write("        }\n");
      out.write("        if(message.type == \"notice\"){       //提示消息\n");
      out.write("            showNotice(message.message);\n");
      out.write("        }\n");
      out.write("        if(message.list != null && message.list != undefined){      //在线列表\n");
      out.write("            showOnline(message.list);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 展示提示信息\n");
      out.write("     */\n");
      out.write("    function showNotice(notice){\n");
      out.write("        $(\"#chat\").append(\"<div><p class=\\\"am-text-success\\\" style=\\\"text-align:center\\\"><span class=\\\"am-icon-bell\\\"></span> \"+notice+\"</p></div>\");\n");
      out.write("        var chat = $(\"#chat-view\");\n");
      out.write("        chat.scrollTop(chat[0].scrollHeight);   //让聊天区始终滚动到最下面\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 展示会话信息\n");
      out.write("     */\n");
      out.write("    function showChat(message){\n");
      out.write("        var to = message.to == null || message.to == \"\"? \"全体成员\" : message.to;   //获取接收人\n");
      out.write("        var isSef = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' == message.from ? \"am-comment-flip\" : \"\";   //如果是自己则显示在右边,他人信息显示在左边\n");
      out.write("        var html = \"<li class=\\\"am-comment \"+isSef+\" am-comment-primary\\\"><a href=\\\"#link-to-user-home\\\"><img width=\\\"48\\\" height=\\\"48\\\" class=\\\"am-comment-avatar\\\" alt=\\\"\\\" src=\\\"/photos/\"+message.from+\"/\"+message.from+\".jpg\"+\"\\\"  onerror=\\\"this.src='/photos/default/default.jpg'\\\" ></a><div class=\\\"am-comment-main\\\">\\n\" +\n");
      out.write("                \"<header class=\\\"am-comment-hd\\\"><div class=\\\"am-comment-meta\\\">   <a class=\\\"am-comment-author\\\" href=\\\"#link-to-user\\\">\"+message.from+\"</a> 发表于<time> \"+message.time+\"</time> 发送给: \"+to+\" </div></header><div class=\\\"am-comment-bd\\\"> <p>\"+message.content+\"</p></div></div></li>\";\n");
      out.write("        $(\"#chat\").append(html);\n");
      out.write("        $(\"#message\").val(\"\");  //清空输入区\n");
      out.write("        var chat = $(\"#chat-view\");\n");
      out.write("        chat.scrollTop(chat[0].scrollHeight);   //让聊天区始终滚动到最下面\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 展示在线列表\n");
      out.write("     \n");
      out.write("     \n");
      out.write("     */\n");
      out.write("    function showOnline(list){\n");
      out.write("        $(\"#list\").html(\"\");    //清空在线列表\n");
      out.write("        $.each(list, function(index, item){     //添加私聊按钮\n");
      out.write("            var li = \"<li>\"+item+\"</li>\";\n");
      out.write("            if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' != item){    //排除自己\n");
      out.write("                li = \"<li>\"+item+\" <button type=\\\"button\\\" class=\\\"am-btn am-btn-xs am-btn-primary am-round\\\" onclick=\\\"addChat('\"+item+\"');\\\"><span class=\\\"am-icon-phone\\\"><span> 私聊</button></li>\";\n");
      out.write("            }\n");
      out.write("            $(\"#list\").append(li);\n");
      out.write("        });\n");
      out.write("        $(\"#onlinenum\").text($(\"#list li\").length);     //获取在线人数\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 图灵机器人\n");
      out.write("     * @param message\n");
      out.write("     */\n");
      out.write("    function tuling(message){\n");
      out.write("        var html;\n");
      out.write("        $.getJSON(\"http://www.tuling123.com/openapi/api?key=6ad8b4d96861f17d68270216c880d5e3&info=\" + message,function(data){\n");
      out.write("            if(data.code == 100000){\n");
      out.write("                html = \"<li class=\\\"am-comment am-comment-primary\\\"><a href=\\\"#link-to-user-home\\\"><img width=\\\"48\\\" height=\\\"48\\\" class=\\\"am-comment-avatar\\\" alt=\\\"\\\" src=\\\"/photos/robot/robot.jpg\"+\"\\\"></a><div class=\\\"am-comment-main\\\">\\n\" +\n");
      out.write("                        \"<header class=\\\"am-comment-hd\\\"><div class=\\\"am-comment-meta\\\">   <a class=\\\"am-comment-author\\\" href=\\\"#link-to-user\\\">Robot</a> 发表于<time> \"+getDateFull()+\"</time> 发送给: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div></header><div class=\\\"am-comment-bd\\\"> <p>\"+data.text+\"</p></div></div></li>\";\n");
      out.write("            }\n");
      out.write("            if(data.code == 200000){\n");
      out.write("                html = \"<li class=\\\"am-comment am-comment-primary\\\"><a href=\\\"#link-to-user-home\\\"><img width=\\\"48\\\" height=\\\"48\\\" class=\\\"am-comment-avatar\\\" alt=\\\"\\\" src=\\\"/photos/robot/robot.jpg\"+\"\\\"></a><div class=\\\"am-comment-main\\\">\\n\" +\n");
      out.write("                        \"<header class=\\\"am-comment-hd\\\"><div class=\\\"am-comment-meta\\\">   <a class=\\\"am-comment-author\\\" href=\\\"#link-to-user\\\">Robot</a> 发表于<time> \"+getDateFull()+\"</time> 发送给: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div></header><div class=\\\"am-comment-bd\\\"> <p>\"+data.text+\"</p><a href=\\\"\"+data.url+\"\\\" target=\\\"_blank\\\">\"+data.url+\"</a></div></div></li>\";\n");
      out.write("            }\n");
      out.write("            $(\"#chat\").append(html);\n");
      out.write("            var chat = $(\"#chat-view\");\n");
      out.write("            chat.scrollTop(chat[0].scrollHeight);\n");
      out.write("            $(\"#message\").val(\"\");  //清空输入区\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 添加接收人\n");
      out.write("     */\n");
      out.write("    function addChat(user){\n");
      out.write("        var sendto = $(\"#sendto\");\n");
      out.write("        var receive = sendto.text() == \"全体成员\" ? \"\" : sendto.text() + \",\";\n");
      out.write("        if(receive.indexOf(user) == -1){    //排除重复\n");
      out.write("            sendto.text(receive + user);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    /**\n");
      out.write("     * 清空聊天区\n");
      out.write("     */\n");
      out.write("    function clearConsole(){\n");
      out.write("        $(\"#chat\").html(\"\");\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function appendZero(s){return (\"00\"+ s).substr((s+\"\").length);}  //补0函数\n");
      out.write("\n");
      out.write("    function getDateFull(){\n");
      out.write("        var date = new Date();\n");
      out.write("        var currentdate = date.getFullYear() + \"-\" + appendZero(date.getMonth() + 1) + \"-\" + appendZero(date.getDate()) + \" \" + appendZero(date.getHours()) + \":\" + appendZero(date.getMinutes()) + \":\" + appendZero(date.getSeconds());\n");
      out.write("        return currentdate;\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/view/index.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /WEB-INF/view/index.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/index.jsp(3,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
