/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.52
 * Generated at: 2018-05-29 11:58:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class info_002dsetting_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/F:/java文件/tomcat/tomcat8/apache-tomcat-8.0.52/webapps/WebChat-master/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1526397396813L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>WebChat | 个人设置</title>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/commonfile.jsp", out, false);
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/header.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"am-cf admin-main\">\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/sidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <!-- content start -->\n");
      out.write("    <div class=\"admin-content\">\n");
      out.write("\n");
      out.write("        <div class=\"am-cf am-padding\">\n");
      out.write("            <div class=\"am-fl am-cf\"><strong class=\"am-text-primary am-text-lg\">个人设置</strong> / <small>form</small></div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"am-tabs am-margin\" data-am-tabs>\n");
      out.write("            <ul class=\"am-tabs-nav am-nav am-nav-tabs\">\n");
      out.write("                <li class=\"am-active\"><a href=\"#tab1\">基本信息</a></li>\n");
      out.write("                <li><a href=\"#tab2\">修改头像</a></li>\n");
      out.write("                <li><a href=\"#tab3\">修改密码</a></li>\n");
      out.write("            </ul>\n");
      out.write("\n");
      out.write("            <div class=\"am-tabs-bd\">\n");
      out.write("                <div class=\"am-tab-panel am-fade am-in am-active\" id=\"tab1\">\n");
      out.write("                    ");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    <form class=\"am-form am-form-horizontal\" id=\"information-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/update\" method=\"post\" data-am-validator>\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <label for=\"userid\" class=\"am-u-sm-2 am-form-label\">用户名</label>\n");
      out.write("                            <div class=\"am-u-sm-10\">\n");
      out.write("                                <input type=\"text\" id=\"userid\" name=\"userid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" disabled>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <label for=\"nickname\" class=\"am-u-sm-2 am-form-label\">昵称</label>\n");
      out.write("                            <div class=\"am-u-sm-10\">\n");
      out.write("                                <input type=\"text\" id=\"nickname\" name=\"nickname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required placeholder=\"这里输入你的昵称...\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <label for=\"sex\" class=\"am-u-sm-2 am-form-label\">性别</label>\n");
      out.write("                            <div class=\"am-u-sm-10\">\n");
      out.write("                                <select id=\"sex\" name=\"sex\" data-am-selected>\n");
      out.write("                                    <option selected></option>\n");
      out.write("                                    <option value=\"1\">男</option>\n");
      out.write("                                    <option value=\"0\">女</option>\n");
      out.write("                                    <option value=\"-1\">保密</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("                            <script>\n");
      out.write("                                $('#sex').find('option').eq(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.sex}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(").attr('selected', true);\n");
      out.write("                            </script>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <label for=\"age\" class=\"am-u-sm-2 am-form-label\">年龄</label>\n");
      out.write("                            <div class=\"am-u-sm-10\">\n");
      out.write("                                <input type=\"number\" id=\"age\" name=\"age\" min=\"1\" max=\"100\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.age}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"这里输入你的年龄...\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <label for=\"profile\" class=\"am-u-sm-2 am-form-label\">个性签名</label>\n");
      out.write("                            <div class=\"am-u-sm-10\">\n");
      out.write("                                <textarea class=\"\" id=\"profile\" name=\"profile\" rows=\"5\" placeholder=\"这里可以写下你的个性签名...\"></textarea>\n");
      out.write("                            </div>\n");
      out.write("                            <script>\n");
      out.write("                                $(\"#profile\").val(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\n");
      out.write("                            </script>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <div class=\"am-u-sm-10 am-u-sm-offset-2\">\n");
      out.write("                                <button type=\"submit\" class=\"am-btn am-round am-btn-success\"><span class=\"am-icon-send\"></span> 提交</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"am-tab-panel am-fade\" id=\"tab2\">\n");
      out.write("                    <form class=\"am-form am-form-horizontal\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/upload\" enctype=\"multipart/form-data\" method=\"post\" onsubmit=\"return checkFileType();\" style=\"text-align: center;\">\n");
      out.write("                        <div style=\"text-align: center;margin-bottom: 10px\">\n");
      out.write("                            <img class=\"am-circle\" src=\"/photos/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".jpg\" onerror=\"this.src='/photos/default/default.jpg'\" width=\"140\" height=\"140\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"am-form-group am-form-file\">\n");
      out.write("                            <button type=\"button\" class=\"am-btn am-btn-secondary am-btn-sm\">\n");
      out.write("                                <i class=\"am-icon-cloud-upload\"></i> 选择要上传的文件</button>\n");
      out.write("                            <input id=\"file\" type=\"file\" name=\"file\" multiple>\n");
      out.write("                        </div>\n");
      out.write("                        <div id=\"file-list\"></div>\n");
      out.write("                        <button type=\"submit\" class=\"am-btn am-round am-btn-success\"><span class=\"am-icon-upload\"></span> 上传头像</button>\n");
      out.write("                        <script>\n");
      out.write("                            $(function() {\n");
      out.write("                                $('#file').on('change', function() {\n");
      out.write("                                    var fileNames = '';\n");
      out.write("                                    $.each(this.files, function() {\n");
      out.write("                                        fileNames += '<span class=\"am-badge\">' + this.name + '</span> ';\n");
      out.write("                                    });\n");
      out.write("                                    $('#file-list').html(fileNames);\n");
      out.write("                                });\n");
      out.write("                            });\n");
      out.write("                        </script>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"am-tab-panel am-fade\" id=\"tab3\">\n");
      out.write("                    <form class=\"am-form am-form-horizontal\" data-am-validator action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/pass\" method=\"post\">\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <label for=\"password1\" class=\"am-u-sm-2 am-form-label\">原密码</label>\n");
      out.write("                            <div class=\"am-u-sm-10\">\n");
      out.write("                                <input type=\"password\" id=\"password1\" name=\"oldpass\" required placeholder=\"请输入原密码...\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <label for=\"password2\" class=\"am-u-sm-2 am-form-label\">新密码</label>\n");
      out.write("                            <div class=\"am-u-sm-10\">\n");
      out.write("                                <input type=\"password\" id=\"password2\" name=\"newpass\" required placeholder=\"请输入新密码...\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <label for=\"password3\" class=\"am-u-sm-2 am-form-label\">确认新密码</label>\n");
      out.write("                            <div class=\"am-u-sm-10\">\n");
      out.write("                                <input type=\"password\" id=\"password3\" data-equal-to=\"#password2\" required placeholder=\"请确认新密码...\">\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"am-form-group\">\n");
      out.write("                            <div class=\"am-u-sm-10 am-u-sm-offset-2\">\n");
      out.write("                                <button type=\"submit\" class=\"am-btn am-round am-btn-success\"><span class=\"am-icon-send\"></span> 提交修改</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- content end -->\n");
      out.write("</div>\n");
      out.write("<a href=\"#\" class=\"am-show-sm-only admin-menu\" data-am-offcanvas=\"{target: '#admin-offcanvas'}\">\n");
      out.write("    <span class=\"am-icon-btn am-icon-th-list\"></span>\n");
      out.write("</a>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "include/footer.jsp", out, false);
      out.write("\n");
      out.write("<script>\n");
      out.write("    if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"){\n");
      out.write("        layer.msg('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', {\n");
      out.write("            offset: 0,\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"){\n");
      out.write("        layer.msg('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${error}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', {\n");
      out.write("            offset: 0,\n");
      out.write("            shift: 6\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function checkFileType(){\n");
      out.write("        var format = [\"bmp\",\"jpg\",\"gif\",\"png\"];\n");
      out.write("        var filename = $(\"#file\").val();\n");
      out.write("        var ext = filename.substring(filename.lastIndexOf('.') + 1).toLowerCase();\n");
      out.write("        if(jQuery.inArray(ext, format) != -1){\n");
      out.write("            return true;\n");
      out.write("        }else{\n");
      out.write("            layer.msg('头像格式只能是bmp,jpg,gif,png!', {\n");
      out.write("                offset: 0,\n");
      out.write("                shift: 6\n");
      out.write("            });\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/view/info-setting.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /WEB-INF/view/info-setting.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/info-setting.jsp(3,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/view/info-setting.jsp(30,20) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/view/info-setting.jsp(30,20) '${user}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${user}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/view/info-setting.jsp(30,20) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("user");
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
